version: '3.8'

services: 
    pwa:
        build:
            context: './'
            target: 'pwa_dev'
        volumes: 
            - './:/usr/src/pwa:rw,cached'
        ports:
            - target: 3000
              published: ${PORT}
              protocol: tcp
