version: '3.4'

services:
  pwa:
    build:
      context: ./
      target: pwa_dev
    volumes:
      - ./:/usr/src/pwa:rw,cached 
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
